apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app-deployment
  labels:
    app: note-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
      - name: note-app-container
        image: shadabahmed23/my-note-app
        - containerPort: 8000   

---
apiVersion: v1
kind: Service
metadata:
  name: note-app-service


spec:
  type: NodePort
  selector:
    app: note-app

  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
